const colors = {
  light: {
    text: "#0D0D0D",
    tint: "#2563EB",
    background: "#FAFAFA",
    foreground: "#0D0D0D",
    card: "#FFFFFF",
    cardForeground: "#0D0D0D",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F4F8",
    secondaryForeground: "#2D3A4A",
    muted: "#F0F4F8",
    mutedForeground: "#637286",
    accent: "#EBF0FB",
    accentForeground: "#2563EB",
    destructive: "#E53E3E",
    destructiveForeground: "#FFFFFF",
    border: "#DDE3EE",
    input: "#DDE3EE",
  },
  dark: {
    text: "#F2F2F2",
    tint: "#2563EB",
    background: "#0D0D0D",
    foreground: "#F2F2F2",
    card: "#121212",
    cardForeground: "#F2F2F2",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#1C2333",
    secondaryForeground: "#CBD5E0",
    muted: "#191F2E",
    mutedForeground: "#94A3B8",
    accent: "#1A2438",
    accentForeground: "#5B8DEF",
    destructive: "#9B2C2C",
    destructiveForeground: "#FFFFFF",
    border: "#262626",
    input: "#262626",
  },
  radius: 8,
};

export default colors;
